time0.out:usetime0.cpp mytime0.cpp
	g++ usetime0.cpp mytime0.cpp -o time0.out
time1.out:usetime1.cpp mytime1.cpp
	g++ usetime1.cpp mytime1.cpp -o time1.out
time2.out:usetime2.cpp mytime2.cpp
	g++ usetime2.cpp mytime2.cpp -o time2.out
