version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks: 
      - app

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "20002:8080"
    networks:
      - app

networks:
  app:
    external: true
